### ISSUE TITLE
Build in Travis CI fails due to hash mismatch.

### ISSUE THREAD

**Issue by tijme** [Orphis/boost-cmake#27]
Hi there, thanks for the nice integration!

It works perfectly when I use it locally but unfortunately CMake fails on Travis CI. The hash of the downloaded file does not match the required hash. I think it's somehow not possible to download files using CMake on Travis CI.

Have you experienced this problem yourself? And do you maybe know a fix?

**Travis CI log**

    -- Downloading Boost from https://github.com/Orphis/boost-cmake/releases/download/v1.63.0%2B1/boost_1_63_0-1.tar.xz

    CMake Error at lib/boost/cmake/Modules/DownloadBoost.cmake:49 (file):
      file DOWNLOAD HASH mismatch
        for file: [/home/travis/build/my/project/lib/boost/boost_1_63_0-1.tar.xz.tmp]
          expected hash: [bb03ac7d13d6bfae52ac13ceaf54d88aa0c4776611bf60a942947f46aedcdb1a]
            actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
                 status: [1;"Unsupported protocol"]

    Call Stack (most recent call first):
      lib/boost/CMakeLists.txt:10 (include)

    CMake Error at lib/boost/cmake/Modules/DownloadBoost.cmake:59 (message):
      Download failed.  Status: 1 "Unsupported protocol"
      Log:

    Call Stack (most recent call first):
      lib/boost/CMakeLists.txt:10 (include)

    -- Configuring incomplete, errors occurred!
    See also "/home/travis/build/my/project/build-test/CMakeFiles/CMakeOutput.log".
    See also "/home/travis/build/my/project/build-test/CMakeFiles/CMakeError.log".

**Comment by Orphis** [comment]
> Status: 1 "Unsupported protocol"

Looks like your version of CMake doesn't support HTTPS. Which distribution are you using on Travis?
I know the default version on Travis isn't always great, so you could try to fetch the latest CMake version instead and use it, just like I did in this repository's build script.

**Comment by tijme** [comment]
Thanks. It seems to be an issue with CMake support for HTTPS indeed. I now use `dist: trusty` and CMake 3.8 in my Travis CI config, which fixes it. However, I am getting a new error.

    CMake Error at lib/boost/CMakeLists.txt:133 (add_library):
      Cannot find source file:
        /home/travis/build/my/project/lib/boost/boost/boost_1_63_0/libs/graph_parallel/src/allocator.cpp
      Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
      .hxx .in .txx
    Call Stack (most recent call first):
      lib/boost/libs/graph_parallel.cmake:5 (_add_boost_lib)
      lib/boost/CMakeLists.txt:191 (include)

I created a merge request for the fix.

**Comment by Orphis** [comment]
Precise is indeed quite an old distribution going EOL in a little bit more than a month and trusty or anything newer is very much recommended!

**Comment by tijme** [comment]
@Orphis I got everything working now. Thanks for the help.

Just in case anyone runs into the same problems, here are the changes I made to my Travis CI config.

I tested it with CMake 3.8.0-rc2. Please note that the example below uses 3.7.2, which I didn't test yet. As @Orphis mentioned in the comment below, it's better to use 3.7.2 until a stable version of 3.8.0 is released.

    dist: trusty

    before_install:
      - mkdir $HOME/usr
      - export PATH="$HOME/usr/bin:$PATH"
      - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
      - chmod +x cmake-3.7.2-Linux-x86_64.sh
      - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

**Comment by Orphis** [comment]
I wouldn't recommend using the 3.8.0-rc2 though!
3.7.2 is a better choice until 3.8.0 is released.

There are also the tar.gz file you can just download, unpack anywhere and run the binary from instead of downloading an installer. A matter of personal preference though!
