### ISSUE TITLE
Unable to find ICU libraries?

### ISSUE THREAD

**Issue by rcdailey** [Orphis/boost-cmake#31]
I'm using CMake 3.8 rc2 with a toolchain for android NDK r14b on Windows.

Command line:

```
cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="%~dp0/android.toolchain.cmake"
```

Toolchain:

```
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 15) # API level
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
set(CMAKE_ANDROID_STL_TYPE c++_static)
set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang)

string(REGEX REPLACE "\\\\" "/" ndk_path "$ENV{ANDROID_NDK}")
set(CMAKE_ANDROID_NDK ${ndk_path})

unset(ndk_path)
```

Root `CMakeLists.txt` file:

```
cmake_minimum_required(VERSION 3.7)

add_subdirectory(boost-cmake)

set(CMAKE_CXX_STANDARD 14)

set(project_name ndk_test)
project(${project_name})
add_library(${project_name} SHARED main.cpp)
target_link_libraries(${project_name} PUBLIC Boost::filesystem)
```

Logs when running CMake:

```
-- Downloading Boost from https://github.com/Orphis/boost-cmake/releases/download/v1.63.0%2B1/boost_1_63_0-1.tar.xz
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Extracting Boost archive...
-- Boost found: 1.63.0 C:/code/ndk_test/boost-cmake/boost/boost_1_63_0
-- Boost found: 1.63.0 C:/code/ndk_test/boost-cmake/boost/boost_1_63_0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- The ASM compiler identification is Clang
-- Found assembler: C:/android/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Found ZLIB: C:/android/ndk/platforms/android-15/arch-arm/usr/lib/libz.so (found version "1.2.3")
-- The following ICU libraries were not found:
--   uc (required)
--   dt (required)
--   i18n (required)
-- Failed to find all ICU components (missing:  ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND)
-- Boost locale unsupported on platform: need either iconv or ICU.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/code/ndk_test/build
```

It is saying it has failed to find ICU and it didn't build boost. I'm not sure why bzip, zlib, and ICU libraries are even being searched for since you can build boost without them. I just want to build boost using the toolchain defined by my toolchain file.

Why is your boost-cmake script not working?

**Comment by Orphis** [comment]
Hi!

It is working! It is actually trying to setup all the various libraries from Boost, one of them being Boost::locale and it can use ICU or iconv, so it searches for them, and indeed fail since they aren't provided by the Android NDK.
If you don't want to use that module, then you can ignore the error.

BZip2 is an optional dependency used by Boost::iostreams if I remember correctly, same deal, if you don't use it, it's fine to ignore the message.

I guess I could try to silence those messages so it doesn't look like an error has occurred.

In any case, when you run "ninja", does it build? That's the only thing you should care about in the end :)

**Comment by rcdailey** [comment]
Let me make sure I understand something first...

Does your CMake script also build the binaries? For example, the *.so or *.a files needed for the portions of boost that are not header-only?

**Comment by Orphis** [comment]
Yes, it builds whichever libraries you depend on. That's the main purpose of the project actually!
CMake will automatically build and link them to your targets when you use `target_link_libraries(foo PUBLIC Boost::<modulename>)`.

If you don't use a library, then it won't be built (unless you ask to manually). It will build static libraries so either .lib on Windows or .a everywhere else.

**Comment by rcdailey** [comment]
Cool, very nice actually. It is indeed working. It was such a pain in the ass to try to get boost building using bjam.

My only complaint is that boost builds in real time with the rest of my targets, instead of being treated as third party libraries (with include dirs and libraries). I don't like the Boost_ targets showing up in my visual studio solution.

Do you have a mechanism that will hide these or somehow allow these to be built externally from my normal projects? Maybe via a super build?

**Comment by rcdailey** [comment]
Example:

![image](https://cloud.githubusercontent.com/assets/1768054/24432354/2b076fac-13e7-11e7-992e-df0003399737.png)

**Comment by Orphis** [comment]
Well, it is actually necessary to build it with the rest of the project since you may be using lots of different build flags that will require to rebuild. Building Boost is usually quite fast so it shouldn't take a significant amount of time.

As for the targets that show up, I can put them in a solution folder. Thanks for reminding me of this!

**Comment by rcdailey** [comment]
Thank you very much for your quick help. I am going to use this at our company to support NDK, since this is very easy to maintain (no separate building of boost libraries which is good!)

I will provide PRs for any issues I find in an effort to help you maintain the project. Thank you again!!

**Comment by Orphis** [comment]
Please have a look at #32 to fix the clutter. It works for me with Xcode and I would like to know what you think of it!

**Comment by Orphis** [comment]
@rcdailey Also, something I still haven't documented that is relevant in a company context: You can change the URL for the Boost source archive by changing some CMake variables, for example to point to an internal company mirror. 
Let me know if you are interested and I'll then try to prioritize that next :)
