### ISSUE TITLE
Missing libs/graph_parallel/src/allocator.cpp

### ISSUE THREAD

**Issue by kybu** [Orphis/boost-cmake#33]
Hi,

I am getting following error when running cmake generator on Linux. My main cmake list is very simple, just one executable and `boost-cmake` is added through `add_subdirectory`

    CMake Error at external/boost-cmake/cmake/Modules/AddBoostLib.cmake:7 (add_library):
    Cannot find source file:

    <pathtosrcs>/external/boost-cmake/boost/boost_1_63_0/libs/graph_parallel/src/allocator.cpp

    Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
      .hxx .in .txx
    Call Stack (most recent call first):
      external/boost-cmake/libs/graph_parallel.cmake:5 (_add_boost_lib)
      external/boost-cmake/CMakeLists.txt:61 (include)

**Comment by kybu** [comment]
Sry, my bad. I wasn't on the latest commit.

**Comment by Orphis** [comment]
No worries :)
