### ISSUE TITLE
`iconv_open` required at runtime?

### ISSUE THREAD

**Issue by rcdailey** [Orphis/boost-cmake#36]
Which parts of boost require `iconv_open` library at runtime? My Android library is trying to load it and it fails:

```
 dalvikvm: Trying to load lib /data/data/com.ttm.zapp/files/../lib/libzApp.so 0x41d94658
 dalvikvm: dlopen("/data/data/com.ttm.zapp/files/../lib/libzApp.so") failed: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "iconv_open" referenced by "libzApp.so"...
```

Doing a grep reveals that Boost Locale is using it, but I do not include these headers directly in my program. Which libs are requiring it? How can I disable it?

**Comment by Orphis** [comment]
It should be Boost::locale. To figure out exactly which object file is using it, you could check your .a and .o files with "nm -a" and search for a line with "U iconv_open".

**Comment by Orphis** [comment]
Sorry, I meant "U _iconv_open".

**Comment by rcdailey** [comment]
Thanks, I figured it out. It wasn't boost after all, but another one of my libraries. Your commands were very helpful!

**Comment by Orphis** [comment]
Great that you figured it out! I was thinking that since you used CrystaX and it provides iconv when the regular NDK doesn't, it might come from it and something hadn't been rebuilt properly. Was that it? :)

**Comment by rcdailey** [comment]
Yep that's absolutely it!
