### ISSUE TITLE
Build failed with boost::locale

### ISSUE THREAD

**Issue by ghost** [Orphis/boost-cmake#39]
Hi,
I just added the boost::locale to my project as dependency and the build failed. It seems that boost::unique_lock is not found during the build. The other selected libraries (log, program_options) works fine. Boost::thread is compiled as well.

-- The CXX compiler identification is GNU 6.3.0
-- (K)ubuntu 17.04
-- CMake 3.8.2
-- failed with pre-set url and with sourcefource archive
-- tried with ICU, ICONV, STD and POSIX-Backend

```/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp: In member function ‘std::locale boost::locale::generator::generate(const std::locale&, const string&) const’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:122:17: error: ‘unique_lock’ is not a member of ‘boost’
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                 ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:122:48: error: expected primary-expression before ‘>’ token
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:122:70: error: ‘guard’ was not declared in this scope
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                                      ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:150:17: error: ‘unique_lock’ is not a member of ‘boost’
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                 ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:150:48: error: expected primary-expression before ‘>’ token
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:150:70: error: ‘guard’ was not declared in this scope
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                                      ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp: In function ‘std::__cxx11::string boost::locale::time_zone::global()’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:447:9: error: ‘unique_lock’ is not a member of ‘boost’
         boost::unique_lock<boost::mutex> lock(tz_mutex());
         ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:447:40: error: expected primary-expression before ‘>’ token
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                        ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:447:57: error: ‘lock’ was not declared in this scope
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                                         ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp: In function ‘std::__cxx11::string boost::locale::time_zone::global(const string&)’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:453:9: error: ‘unique_lock’ is not a member of ‘boost’
         boost::unique_lock<boost::mutex> lock(tz_mutex());
         ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:453:40: error: expected primary-expression before ‘>’ token
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                        ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:453:57: error: ‘lock’ was not declared in this scope
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                                         ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp: In static member function ‘static boost::locale::localization_backend_manager boost::locale::localization_backend_manager::global()’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:248:13: error: ‘unique_lock’ is not a member of ‘boost’
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
             ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:248:44: error: expected primary-expression before ‘>’ token
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
                                            ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:248:87: error: ‘lock’ was not declared in this scope
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
                                                                                       ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp: In static member function ‘static boost::locale::localization_backend_manager boost::locale::localization_backend_manager::global(const boost::locale::localization_backend_manager&)’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:254:13: error: ‘unique_lock’ is not a member of ‘boost’
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
             ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:254:44: error: expected primary-expression before ‘>’ token
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
                                            ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:254:87: error: ‘lock’ was not declared in this scope
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
```

**Comment by ghost** [comment]
I found the reason why this failed:

The three files include thread/mutex.hpp. This only includes thread/lock_types.hpp `#if defined BOOST_THREAD_PROVIDES_NESTED_LOCKS`. 
Adding `DEFINE_PRIVATE BOOST_THREAD_PROVIDES_NESTED_LOCKS=1` to locale.cmake -> _add_boost_lib fixes the problem, you may consider to add this line.

**Comment by Orphis** [comment]
Thanks for the report! 

Alright, I'll have a look when I'm back at my computer. But I notice you are using 1.63, any specific reason why? Also, that define should be probably defined somewhere else in the module preprocessor configuration. It's weird to add a thread specific define to locale!

**Comment by ghost** [comment]
I used 1.63 because 1.64 also failed with the same reason, just experimenting with it ;)
I will take a look in the preprocessor configuration and will report it back if I find anything new. Thanks for the fast reply!

**Comment by ghost** [comment]
Yeah, i didn't inspect your CMakeLists.txt far enough. At the very bottom
`set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS BOOST_THREAD_PROVIDES_NESTED_LOCKS)`
should be added. Right next to some other thread specific defines like `BOOST_THREAD_USES_CHRONO` and `BOOST_THREAD_PROVIDES_EXECUTORS`.

**Comment by Orphis** [comment]
Those should be moved to the thread library at some point, it's legacy that I 'red to clean up. Let me know if you find something, or I'll take care of it in a few hours.

**Comment by ghost** [comment]
`BOOST_THREAD_PROVIDES_NESTED_LOCKS` enables some [deprecated features](http://www.boost.org/doc/libs/1_64_0/doc/html/thread/build.html#thread.build.configuration.nested_lock), which are required for compiling boost::locale so in this case, adding it to boost::locale might be the better option.

**Comment by Orphis** [comment]
Can you actually provide me the full command line used for compiling the file?
`boost/thread/locks.hpp` will always define `boost::unique_lock` regardless of that define. Maybe it's just a missing include?

**Comment by Orphis** [comment]
So yes, they only include `boost/thread/mutex.hpp`, which doesn't include the header for `unique_lock` unless that other define is set. The proper fix is actually to include `boost/thread/locks.hpp` in `src/shared/generator.cpp` and other files.

I can make a patch tomorrow to fix the issue, send it upstream and patch the release package here.

**Comment by ghost** [comment]
As far as I can see, adding the define is the only clean way to compile boost::locale without modifying the actually boost source, which is a no-go. This way `scoped_lock` (which is nothing else than a typedef to `unique_lock<mutex>`) will be enabled, even if `BOOST_THREAD_VERSION` is [set to 4](https://github.com/Orphis/boost-cmake/blob/master/CMakeLists.txt#L71). 
Adding the define in locale.cmake (the way I did it in the PR) won't break anything because the define only needs to be private since the `scope_lock` is only used in source files rather than in header files.

**Comment by Orphis** [comment]
Modifying the source is fine, if it's cherry-picking a patch that is going to be added to the next release that fixes some issue.
Fixing the actual code instead of using a workaround that adds some deprecated feature back is the clean way.

**Comment by ghost** [comment]
I link your PR to boost::locale for completness: boostorg/locale#16

**Comment by Orphis** [comment]
Also, I can note that the tests didn't catch the issue as I compile with default Boost Thread version but use v4 in projects (to match the std::thread API). And v4 doesn't work with Boost Log. I'll try to make a patch to fix that too.

**Comment by Orphis** [comment]
Patch merged upstream, I'll provide an updated Boost archive with this backported fix soon.

**Comment by Orphis** [comment]
This should be fixed with #48

**Comment by mattlathrop** [comment]
I am having this issue with the master branch. Any reason this would still be happening?

**Comment by Orphis** [comment]
They might have broken it again. Can you send a sample project and source that repro the issue?

**Comment by mattlathrop** [comment]
The attached file should generate the error. Here are the steps I used to reproduce the issue:
1. Configure/Generate Project using Visual Studio 2015 x64
2. Build project "boost" in visual studio 2015.
3. locale fails to build. I can confirm all other modules build successfully. 

[helloworld.zip](https://github.com/Orphis/boost-cmake/files/3178557/helloworld.zip)

**Comment by jdumas** [comment]
I'm encountering a similar issue using the version from the current tip of the master branch (70b12f6)
