### ISSUE TITLE
Build Boost Log

### ISSUE THREAD

**Issue by Orphis** [Orphis/boost-cmake#4]

**Comment by Orphis** [comment]
Boost log builds in a branch right now, need to add tests for it!

**Comment by kybu** [comment]
I tried `Boost::log` library from the `log` branch and it was working for me. Thanks.

Would it be possible to add `Boost::log_setup` as well? It depends on `Boost::log` and there is some extra stuff for logger initialization.

**Comment by Orphis** [comment]
It's possible, sure! I'm on holidays and will resume work when I'm back next week :)

**Comment by Orphis** [comment]
Fixed with #35
