### ISSUE TITLE
CMAKE_ASM_COMPILE_OBJECT "missing" error in CMake

### ISSUE THREAD

**Issue by rcdailey** [Orphis/boost-cmake#42]
I get the following error in CMake when I `add_subdirectory()` on your repo:

```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILE_OBJECT
```

If I do not `add_subdirectory()`, this error goes away. Do you have any idea what is causing this?

**Comment by rcdailey** [comment]
I did some toying around and made some changes that fix it.

I commented this out in the root CMakeLists.txt:

```
set(CMAKE_ASM_COMPILER_TARGET "${CMAKE_CXX_COMPILER_TARGET}")
```

Then in `lib/context.cmake`, commented out each call to `enable_language()`. Are these required? I'm using CMake 3.9.0-rc5.

**Comment by Orphis** [comment]
No, this was fixed in 3.7 or 3.8, I should add a version check actually.
The `enable_language()` are probably required. What errors do they cause?

**Comment by rcdailey** [comment]
I posted the error above a little bit. All I can tell you is that it doesn't work. I'm assuming by 3.7 3.8 you mean CMake version.

**Comment by Orphis** [comment]
Is this still an issue?

**Comment by rcdailey** [comment]
Probably not, since my fork of your repo no longer has these changes, and seems to work fine. I'll close for now. If I run into the issue again, I'll reopen.

**Comment by ivakyb** [comment]
I have met the same problem with Zephyr project.  
[`enable_languages`](https://cmake.org/cmake/help/latest/command/enable_language.html) helped. Thank you, @Orphis 

    enable_language( C CXX ASM )
