### ISSUE TITLE
Upgrade to Boost 1.66

### ISSUE THREAD

**Issue by Orphis** [Orphis/boost-cmake#48]

**Comment by rcdailey** [comment]
Any possibility of this happening soon? The main motivation is for proper VS2017 support, since Boost 1.63 has a silly warning during compilation about unknown compiler version.

**Comment by Orphis** [comment]
Sure, if I get to sit down a bit and rest first. Spent a lot of time traveling recently!

**Comment by rcdailey** [comment]
Should I consider this project dead? I've waited months for updates but none happen. I hate the idea of having to build boost the "official" way, but at this point I need 1.66 or newer because of some issues compiling for Android NDK. Your boost 1.66 branch won't build against the NDK due to an open issue on boost filesystem. I'd like to try 1.65 but I can't do that either :(

**Comment by macdew** [comment]
We've upgraded to Boost 1.65.1, though admittedly we use very few boost modules...  Is there a particular module that's failing to build for you?

**Comment by darkr4y** [comment]
1.66 added the beast which is a low level http module , its useful , please support 1.66 thx.

**Comment by rcdailey** [comment]
I'm gonna go ahead and say this project is dead.

**Comment by macdew** [comment]
We've just updated to Boost 1.67.0 (with some patches to work with Visual Studio 2017 and /permissive- build flag).  Again, this library worked fine for us.

Have you tried writing your own libs definition file for Beast?  This library isn't rocket science, it's open source and you could contribute?

**Comment by Orphis** [comment]
Would you mind sending a PR for 1.67.0 please? I have to admit I'm swamped with other work and have little time to allocate to this.

**Comment by macdew** [comment]
We only use boost graph & regex, and neither of those libs required changing.  I'll see if I can find some time this weekend to do a more thorough review of existing & new modules

**Comment by Orphis** [comment]
It's fine to be missing new libraries, but existing ones should probably work.

**Comment by palmerc** [comment]
I'll make a PR for 1.67.0

**Comment by Orphis** [comment]
We now have 1.67.0 thanks to @palmerc !

**Comment by rcdailey** [comment]
Originally reported in #39, I am getting locale failures on Windows using MSVC 15.7:

```
18>e:\code\frontend\msvc_2017\core\thirdparty\boost\source\boost\boost_1_67_0\libs\locale\src\win32\lcid.cpp(89): error C2039: 'unique_lock': is not a member of 'boost'
18>e:\code\frontend\msvc_2017\core\thirdparty\boost\source\boost\boost_1_67_0\libs\locale\src\win32\lcid.cpp(24): note: see declaration of 'boost'
18>e:\code\frontend\msvc_2017\core\thirdparty\boost\source\boost\boost_1_67_0\libs\locale\src\win32\lcid.cpp(89): error C2065: 'unique_lock': undeclared identifier
18>e:\code\frontend\msvc_2017\core\thirdparty\boost\source\boost\boost_1_67_0\libs\locale\src\win32\lcid.cpp(89): error C2275: 'boost::mutex': illegal use of this type as an expression
18>e:\code\frontend\msvc_2017\core\thirdparty\boost\source\boost\boost_1_67_0\libs\locale\src\win32\lcid.cpp(89): note: see declaration of 'boost::mutex'
18>e:\code\frontend\msvc_2017\core\thirdparty\boost\source\boost\boost_1_67_0\libs\locale\src\win32\lcid.cpp(89): error C3861: 'lock': identifier not found
```

**Comment by rcdailey** [comment]
I found out the problem. I wasn't able to reproduce the issues above in the standalone build, and the reason is because of this code at the bottom of the root `CMakeLists.txt`:

```
# TODO: Move those to option() calls in the right file
if(NOT BOOST_STANDALONE)
  # Compilation options required by all platforms
  set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS $<$<CONFIG:Release>:BOOST_DISABLE_ASSERT>)
  set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS BOOST_SYSTEM_NO_DEPRECATED)
  set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS BOOST_THREAD_VERSION=4)
  set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS BOOST_THREAD_USES_CHRONO)
  set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS BOOST_THREAD_PROVIDES_EXECUTORS)
endif()
```

If I comment out all of the compile definitions above, everything builds fine.

**Comment by rcdailey** [comment]
So a little more analysis. It's actually this specific line that is causing the compiler error:

    set_property(TARGET Boost::boost APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS BOOST_THREAD_VERSION=4)

If I comment this out, later on I get linker errors:

```
29>Services.lib(SynapseSubmission.obj) : error LNK2019: unresolved external symbol _BCryptCloseAlgorithmProvider@8 referenced in function "public: __thiscall boost::uuids::detail::random_provider_base::~random_provider_base(void)" (??1random_provider_base@detail@uuids@boost@@QAE@XZ)
29>Services.lib(SynapseSubmission.obj) : error LNK2019: unresolved external symbol _BCryptGenRandom@16 referenced in function "public: void __thiscall boost::uuids::detail::random_provider_base::get_random_bytes(void *,unsigned int)" (?get_random_bytes@random_provider_base@detail@uuids@boost@@QAEXPAXI@Z)
29>Services.lib(SynapseSubmission.obj) : error LNK2019: unresolved external symbol _BCryptOpenAlgorithmProvider@16 referenced in function "public: __thiscall boost::uuids::detail::random_provider_base::random_provider_base(void)" (??0random_provider_base@detail@uuids@boost@@QAE@XZ)
29>E:\code\frontend\msvc_2017\output\bin\Debug\Test_Services.exe : fatal error LNK1120: 3 unresolved externals
```

So from my perspective, Boost is busted here and I'm not sure what the issue is. How did you guys get it working?
