### ISSUE TITLE
Boost log & pthread_mutex_robust.cpp: Should it be optional?

### ISSUE THREAD

**Issue by helmesjo** [Orphis/boost-cmake#49]
I'm having issues with boost log, more specifically [this command](https://github.com/Orphis/boost-cmake/blob/552ddadbfb0e46b03fcea95f71eb4393d4d73344/libs/log.cmake#L67) which expects the file _libs/log/config/pthread-mutex-robust/pthread_mutex_robust.cpp_ to be present, which it's not when boost BCP extracts the required subset of a bunch of modules (some of which use boost log).

Is this a bug with BCP, or should that command perhaps be wrapped in a if-file-exists statement?

_Note: I don't know more about the file than the name + command suggests._

**Comment by Orphis** [comment]
Well, if you are supposed to compile the module after running BCP, then you should have this file to be able to run the feature test detection.
We can workaround this issue, but I'm not sure then how to detect them anymore.

**Comment by helmesjo** [comment]
In other words: It's a bug (or inconsistency with how the lookup works) with BCP and I should probably manually copy the config-folder in the case of boost *log*? 
Or probably pass log explicitly to bcp, which seems to properly copy everything needed.
