### ISSUE TITLE
Adding Boost 1.xx.x support, what's the approach?

### ISSUE THREAD

**Issue by helmesjo** [Orphis/boost-cmake#50]
After a lot of headaches I've found that a library I depend upon depends upon boost, but it uses some now deprecated & deleted utilities. Officially it's only supporting ~1.51.0. The oldest version of "modular boost" actually building properly is 1.56.0, however, so that's what I'm stuck with (hoping it'll work).

So, I want to add support for this version in boost-cmake so I can link it. What's your typical approach? 

I've run [boostdep](http://www.boost.org/doc/libs/1_65_1/tools/boostdep/doc/html/index.html) and listed the _[--primary](http://www.boost.org/doc/libs/1_65_1/tools/boostdep/doc/html/index.html#boostdep.reference.primary)_ dependencies for some of the libs (in 1.65.0) but can't really find a pattern between what boostdep lists (looking only at 'buildable' libs, not header-onlys that are in Boost::boost) and what you've linked manually. 

What gives? Will give this a try soon enough, just thought I'd check in before getting knee deep in!

**Comment by Orphis** [comment]
I would say to update your dependency for a modern Boost. Old versions are not very interesting for a project like this. It's over 5 years old and probably doesn't support mobile platforms well or any current compilers.

Of course, feel free to fork it and change whatever is needed of course for your usecase, but it's certainly easier to update the other library than coerce Boost to work with current compilers.

For newer versions, it's usually just drop the new archive, use it and see if the tests pass, update the build scripts as necessary for new files and new required build flags.

**Comment by helmesjo** [comment]
Yeah, I hear you! This is however exclusively for an [external dependency](https://github.com/cucumber/cucumber-cpp), and I want to modify close to nothing or in "worst case" make a pull request that gets merged (private temp-fixes is not an option). I started a [discussion ](https://github.com/cucumber/cucumber-cpp/issues/171) about supporting a newer version and it wasn't out of the question, but support for boost **1.46** (!) had to be preserved. This however presumes that there aren't a lot other things to #ifndef... 
That's why I hoped to just get 1.56 building first and foremost!

As you say, that version is also terribly old but this dependency on legacy boost is _only_ for this one framework. If I ever fall into using boost myself in any project, it will of course target a modern version.

Anyways, I'll give it a try with the help of [boostdep ](http://www.boost.org/doc/libs/1_65_1/tools/boostdep/doc/html/index.html) and we'll see how it goes!

**Comment by Orphis** [comment]
In the case of that library, a simple ifdef around the Boost version should be enough to fix it for newer versions, and I would recommend that approach.

But another approach is possible, which would be to define BOOST_THREAD_USES_DATETIME, which will re-add the missing functions back. Functionality is rarely removed from Boost and usually hidden behind some flags.

**Comment by helmesjo** [comment]
Alright thanks, I'll take a look at it.
