### ISSUE TITLE
user-defined BOOST_LIBS_OPTIONAL

### ISSUE THREAD

**Issue by vglavnyy** [Orphis/boost-cmake#51]
Is it possible add support for a user-defined list of compiled libraries?
Under MSVC all libraries from BOOST_LIBS_OPTIONAL add to the workspace as subprojects. This does not depend from target_link_libraries and takes too much time during compilation.
When I build a user project under linux (gcc/clang), then only used libraries are compiled. This problem exists with compilation under MSVC only.

Somewhere in user space CMakeLissts.txt:
set(BOOST_LIBS_OPTIONAL program_options  system)
add_subdirectory(../external/boost-cmake external/boost)
find_package(Boost REQUIRED)
target_link_libraries(user_target PRIVATE Boost::boost)
target_link_libraries(user_target PRIVATE Boost::program_options)

Inside boost-cmake:
if(NOT BOOST_LIBS_OPTIONAL)
  set(BOOST_LIBS_OPTIONAL
    # Compiled libs
    atomic
     ...
    wave
  )
endif()

**Comment by vglavnyy** [comment]
It can be solved using CACH:
>  type_erasure
>  wave
>  CACHE STRING ""
>)
and at the top level:
> set(BOOST_LIBS_OPTIONAL program_options system CACHE STRING "" FORCE)

**Comment by Orphis** [comment]
Feel free to send a pull request for this!

**Comment by kozlosoft** [comment]
@Orphis can you check pull request on that, please?
