### ISSUE TITLE
Small bug when upgrading boost version and using local directory option

### ISSUE THREAD

**Issue by macdew** [Orphis/boost-cmake#53]
First of all, awesome project, it's really inspired us to make better use of CMake!

Following the contribution from @rcdailey  to allow for a locally stored archive (which is how we use it), I think I spotted a small bug in DownloadBoost.cmake

In the block that detects a new version (SHA check mismatch), it does a:   
file(REMOVE "${DOWNLOAD_PATH}")
However, for the local file option, DOWNLOAD_PATH is the archive I'd like to deploy - so it deletes that one in error.

I've fixed this by introducing a new variable after download that stores the downloaded file name in the cache.  Then, when deleting, don't delete DOWNLOAD_PATH but instead delete the previously downloaded file.  Probably best to unset it too.  If only using the local file option, then the download never happens and this variable remains blank, which is fine for me - I don't want our local boost archive deleted...

**Comment by Orphis** [comment]
That download script is a bit hacky, trying to support to many usages at once.
I wonder if I can use ExternalProject to handle that better.

**Comment by Orphis** [comment]
Closing since we moved to FetchContent which should be more robust now.
