### ISSUE TITLE
Download fails when multiple configurations are generated in parallel

### ISSUE THREAD

**Issue by RogueLogix** [Orphis/boost-cmake#71]
When CLion generates the cmake configs it will do so in parallel for each type, i usually have both Debug and Release setup at the same time and the download will fail when they are both running. works fine if i force it to only run one of them. tested with commit d04f7dfd0f5f0d4a2946242be4aa5c04ee5532f9

**Comment by rcdailey** [comment]
You have to set `BOOST_DOWNLOAD_TO_BINARY_DIR` to `ON` (It's off by default). This will ensure that parallel downloads are not affecting the same physical file (which by default is in your `CMAKE_SOURCE_DIR`). This option will make each download go into the respective `CMAKE_BINARY_DIR`. Give it a shot and let me know. There's [a pull request](https://github.com/Orphis/boost-cmake/pull/68) ongoing that will improve this from a configuration standpoint (i.e. your scenario will work by default with no additional configuration needed).

**Comment by RogueLogix** [comment]
while that works, it requires this hacky seeming line before my add_subdirectory to work correctly
```cmake
set(BOOST_DOWNLOAD_TO_BINARY_DIR ON CACHE BOOL "")
```

**Comment by rcdailey** [comment]
That's not hacky at all. It's normal configuration. You have other options
too like using CMake GUI to set it or command line -D option.

**Comment by Orphis** [comment]
Could you just try the #68 and see if it fixes it for you too?

**Comment by Orphis** [comment]
If we don't go down this route, we might have to use file locking to enable multiple processes to run concurrently.

**Comment by RogueLogix** [comment]
that seems to have resolved the issue.
