### ISSUE TITLE
Clarity on README installation

### ISSUE THREAD

**Issue by LeeRuns** [Orphis/boost-cmake#77]
I am working on a windows build using LLVM / Clang
I have tried writing this myself and was making progress, but still getting some strange errors. 
Then i found this repo, and it looks well supported 
here is my problem..
i downloaded source code and eliminated all of the other subdirectories from by current build.

### PROJECT STRUCTURE
/myProj/
/myProj/extern/boost-cmake
/myProj/llvm

extern/CMakeLists.txt 
which utilizes your boost-cmake project 👍 
```
cmake_minimum_required(VERSION 3.11)
#--Project Details---------------------#
project(extern)

#--Sub Project Def---------------------#
add_subdirectory(boost-cmake)
```
this is what i get in return from terminal 
```
cmake ../ -T"LLVM" && cmake --build .
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.16299.
Binary Tree path: C:/~/opt/myProj/llvm
-- Boost found: 1.69.0 C:/~/opt/myProj/llvm/_deps/boost-src
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES) (found version "1.0.6")
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- The following ICU libraries were not found:
--   uc (required)
--   dt (required)
--   i18n (required)
-- Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND) 
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:2025 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
```

So my questions are as follows:
_1. it says could not find Bzip_Libraries, found version 1.0.6; so did it find them or not?_
_2. same question for zlib_
_3. It looks like the ICU Libraries are required, if that is the case then shouldn't the cmake script stop with an error?_
_4. does this not setup boost_root?_

**Comment by LeeRuns** [comment]
I am still having problems when i try to compile an library using boost filesystem my code follows with cmakelists.txt for a project :
```
#--Create Binaries---------------------#
add_executable(	"main${PROJECT_NAME}" 
		${${PROJECT_NAME}_headers}
		${${PROJECT_NAME}_sources}
		) 
#--linker------------------------------#
#boost linking

find_package(Boost COMPONENTS system thread filesystem unit_test_framework REQUIRED)

target_link_libraries("main${PROJECT_NAME}" ${Boost_LIBRARIES})
`

```

I know this works because it builds/compile when i run on CentOS (because i have installed boost libs with yum).   As usual the windows solution is 1000x more complicated.

**Comment by Orphis** [comment]
You are not supposed to use `find_package(Boost)` with the project.

After doing the `add_subdirectory()` call, you can just link against the libraries you want:
`target_link_libraries("main${PROJECT_NAME}" Boost::system Boost::thread Boost::filesystem Boost::unit_test_framework)`.

Note that this way of linking is valid when using `find_package(Boost)` too and should be the preferred method over using `${Boost_LIBRARIES}`.

**Comment by LeeRuns** [comment]
Wow, thanks for the fast response.
For my education here...why is that not preferred?

**Comment by LeeRuns** [comment]
Let me see if I get this... because I keep thinking find_package(boost) should work... 

1. first boost-cmake must be called (here as a add_subproject)

2. once completed all of the boost header files will be pulled down from the url (https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.bz2)  and unzipped thanks to your modules. 

3. now BOOST_ROOT should be identified because you have already set the variables up in Boost-CMake/CMakeLists/txt, 
````
#ADD KEY CMAKE BOOST SEARCH FUNCTIONS
SET (BOOST_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/boost/)
SET (BOOST_INCLUDEDIR ${CMAKE_CURRENT_SOURCE_DIR}/include)
SET (BOOST_LIBRARYDIR ${CMAKE_CURRENT_SOURCE_DIR}/lib)
````

4. now all of the find_package(boost 1.60.0 COMPONENTS pthread system filesystem etc.....) are available because they were defined in code shown in step 3.

_**So why can't i use find_package(Boost) if all of the variables needed are defined in step 3**_

and why do i get this error when i have taken all of the steps above...
` fatal error : 'boost/filesystem.hpp'`

**Comment by Orphis** [comment]
Many good reasons actually:
- This is Boost 1.69, not Boost 1.60
- This is pointing only to the headers, it might work if it was header only, but several modules need to be compiled.
- It is likely that the internal naming of the modules doesn't match what FindBoost.cmake is expecting. It is an implementation detail of the Boost build system that has no good reason to match my internal build. Since you should use "imported" targets to use Boost (as it conveys more information than using variables), it's not really important to match it.
- There would be collisions between the imported targets created by FindBoost and my build scripts as they share the same name (the goal is to replace FindBoost after all, while still being compatible in the essential parts).

It would be better if you shared your CMake files (or some reduced version with no confidential data) so we can fix it. You could have a look at this file I have in another project as an example too: https://github.com/Orphis/RandoBlazer/blob/master/CMakeLists.txt

**Comment by LeeRuns** [comment]
i will need to sanitize first.
That code snippet really helped.  i swapped out  my external project add, and followed your recipe in the top lvl cmake to pull down the code...
as you guessed correctly i cannot post my code here, so i put together a quick project 
you will notice that there are a couple of missing files if you want me to add so that cmake will run i can do that, but i have a feeling you will spot my error quickly.  
[myProj.zip](https://github.com/Orphis/boost-cmake/files/2858053/myProj.zip)

**Comment by Orphis** [comment]
What are the errors that show up when you run cmake on your project?
I don't see any obvious mistakes (though it's late, so I might have missed something), so I'm thinking it could be a cache issue. Can you try creating a new build folder to have a fresh cache?

**Comment by LeeRuns** [comment]
**here is what i have done 2 follow up**
1. deleted entire build directory
2. generated build scripts
`cmake ../ T"LLVM"
`
3. ran build
cmake --build .

**resulting error**:
_t boost/filesystem.hpp file not found_

`
"C:\Users\BooRadley\myProj\llvm\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\BooRadley\myProj\llvm\src\thing\thing.vcxproj" (default target) (12) ->
  C:\Users\BooRadley\myProj\src\thing/thing.h(32): fatal error : 'boost/filesystem.hpp' file not found [C:\Users\BooRadley\myProj\llvm\src\thing\thing.vcxproj]
`
As you can see this is windows so by default it generates the build as a visual studio project.
In step 3 i have also tried 
`cmake --build --config Debug --target ALL_BUILD
`
But i get the same error.  Being logical i then looked inside of my build dir for boost/filesystem.hpp and it is there.. but for some reason the compiler is not seeing it.  I think that there must be some kind of key cmake variable to map to it's location.  Hoping you can recognize it because it appears to be related to the way cmake writes the file dependency structure.

**here is the location of the file "boost/filesystem.hpp" which the build script cannot find...**
```
BooRadley@WishIWereLinux:~/myProj/llvm$ find . -name filesystem.hpp
./_deps/boost-src/boost/filesystem.hpp

```

**here is the structure for the dependencies directory built by cmake**
```
**BooRadley/myProj/llvm$** ls _deps
boost-build
boost-cmake-build
boost-cmake-src
boost-cmake-subbuild
boost-src
boost-subbuild
```

**Comment by Orphis** [comment]
I see that you have 2 targets, one is a library and one is an executable.
You link the executable against the Boost libraries properly, but compiling the library itself (with the same sources) will not work as it isn't linked against the Boost libraries.

If you use Boost in the library, you should link it against Boost and then link your library to your main executable.
If sources specific to the executable use Boost as well, then you should link Boost to it too.

**Comment by LeeRuns** [comment]
any chance you could point me towards a project where you have done this? :)

**Comment by LeeRuns** [comment]
sorry forgot to close this.
