### ISSUE TITLE
403 Forbidden downloading https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2

### ISSUE THREAD

**Issue by jenia81** [Orphis/boost-cmake#88]
I get a 403 Forbidden when downloading the boost libraries from:
https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2

Tried different releases and different zip files

**Comment by Weiming-Hu** [comment]
I have this issue just recently too. It looks like a Boost server issue. Please see it [here](https://github.com/boostorg/boost/issues/299)

**Comment by Weiming-Hu** [comment]
I have set BOOST_URL [example 1](https://github.com/Orphis/boost-cmake/blob/master/README.md#configuration) [example 2](https://github.com/Orphis/boost-cmake/blob/master/CMakeLists.txt#L6) to a different server `https://phoenixnap.dl.sourceforge.net/project/boost/boost/1.66.0/boost_1_66_0.tar.bz2` and at least it is downloading. But then, I have the linking issue at the end of my C++ executable compilation. I'm not sure whether it is because I changed the server.

The latest version `1.72` also gave me the same issue.

**Comment by Weiming-Hu** [comment]
Just to update. This morning, Boost downloading is working.

**Comment by moshe-shahar** [comment]
Not working again:
wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2
```
--2020-03-29 12:26:03--  https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2
Resolving dl.bintray.com (dl.bintray.com)... 52.29.129.139, 52.28.187.224
Connecting to dl.bintray.com (dl.bintray.com)|52.29.129.139|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-29 12:26:04 ERROR 403: Forbidden.

```

**Comment by halehOssadat** [comment]
Mine is not working again!
[https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2](https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2)

**Comment by ghost** [comment]
Mine neither! https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2

**Comment by ghost** [comment]
Okay found out that they moved their filesystem or something. Not referenced in any of the old tutorials and guides I guess.
Here is the new domain that you can simply add your suffix to:

https://boostorg.jfrog.io/artifactory/main/release/

The website that I found the above link:

https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html

**Comment by Orphis** [comment]
Can you send a pull request with the new URL please?

**Comment by Orphis** [comment]
This has been fixed in recent updates, if you are attached to a specific older version of Boost, you should have a fork with the updated URL.

**Comment by EBII** [comment]
i assume that new download link is this 
https://archives.boost.io/release/1.70.0/source/boost_1_70_0.tar.bz2
checksum as gone too
