### ISSUE TITLE
IOS variable 

### ISSUE THREAD

**Issue by Zer0xFF** [Orphis/boost-cmake#9]
I know you probably don’t explicitly mean for people to use the ios cmake toolchain you've included here as part of their project, but it was handy enough since I'm using this as a sobmodule.

however I've noticed that I had to check for IOS_PLATFORM instead IOS to confirm the build is for IOS and IOS seems more inline with current convention and perhaps to defineTARGET_OS_IPHONE and TARGET_IPHONE_SIMULATOR, while the toolchain already checks for this anyway https://github.com/Orphis/boost-cmake/blob/master/cmake/Toolchains/ios.cmake#L35

**Comment by Orphis** [comment]
There's no such convention and this isn't made to be reused elsewhere.
Feel free to copy it and change it to your will though.
